### ISSUE TITLE
UI stops responding when adding chains / processors

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1027]
# Describe the issue
When adding chains or processors the UI will sometimes freeze. It seems to happen when navigating different groups of instrument / plugin.
# To Reproduce
## Steps to reproduce the behavior:
1. Add a chain
2. Select a group and bold press ENTER to toggle displayed engines
3. Enable an engine
4. Press BACK then select the engine just enabled
5. Try to add another chain / processor
 ## Expected behaviour
UI should continue working.
## Actual behaviour
UI freezes.
# Additional context
```
Apr 22 13:54:59 zynthian-v5-64 startx[29311]: Traceback (most recent call last):
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2249, in cuia_thread_task
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.zynswitch_short(i)
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1876, in zynswitch_short
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.screens[self.current_screen].switch_select('S')
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 345, in switch_select
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.click_listbox(None, t)
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 336, in click_listbox
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.select_action(self.index, t)
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_chain_menu.py", line 68, in select_action
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.last_action(t)
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_chain_menu.py", line 71, in add_synth_chain
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.zyngui.modify_chain({"type": "MIDI Synth", "midi_thru": False, "audio_thru": False})
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 865, in modify_chain
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.show_screen("engine")
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 584, in show_screen
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     if not self.screens[screen].build_view():
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_engine.py", line 246, in build_view
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     return super().build_view()
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:            ^^^^^^^^^^^^^^^^^^^^
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 161, in build_view
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     self.fill_list()
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_engine.py", line 265, in fill_list
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:     cats = [self.engine_cats[self.cat_index]]
Apr 22 13:54:59 zynthian-v5-64 startx[29311]:             ~~~~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
Apr 22 13:54:59 zynthian-v5-64 startx[29311]: IndexError: list index out of range
```
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 19% (740M/3792M)
SD Card: 85% (24G/29G)
Temperature: 52.5ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (c575089) 
zynthian-ui: oram (4daa3b2)
zynthian-sys: oram (99700c2)
zynthian-data: oram (97355e2)
zynthian-webconf: oram (3f1dae4)
```

**Comment by jofemodo** [comment]
Sorry, i can't reproduce. I will keep open eyes ...
