### ISSUE TITLE
Midi file import into zynseq not working on latest oram

### ISSUE THREAD

**Issue by sstojos** [zynthian/zynthian-issue-tracking#1060]
I am following the [import instructions from wiki](https://wiki.zynthian.org/index.php/ZynSeq_User_Guide#Import_.2F_Export_MIDI_Files) to load SMF file into zynseq. It always fail (freeze) very early in the load. I thought that maybe something is wrong with my midi file format so I extracted SMF file from sample patterns e.g. “burkina_01” and try to reimport the same - this also fails.

I am on fully updated oram and MINI V2 hardware.

**Comment by riban-bw** [comment]
This is due to change in zynseq addNote:

```
Jun 03 17:07:07 zynthian-v5-64 startx[934]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: ['3', 'R']
Jun 03 17:07:07 zynthian-v5-64 startx[934]: Traceback (most recent call last):
Jun 03 17:07:07 zynthian-v5-64 startx[934]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2285, in cuia_thread_task
Jun 03 17:07:07 zynthian-v5-64 startx[934]:     self.zynswitch_short(i)
Jun 03 17:07:07 zynthian-v5-64 startx[934]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1907, in zynswitch_short
Jun 03 17:07:07 zynthian-v5-64 startx[934]:     self.screens[self.current_screen].switch_select('S')
Jun 03 17:07:07 zynthian-v5-64 startx[934]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_confirm.py", line 122, in switch_select
Jun 03 17:07:07 zynthian-v5-64 startx[934]:     self.callback(self.callback_params)
Jun 03 17:07:07 zynthian-v5-64 startx[934]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_arranger.py", line 402, in do_import_smf
Jun 03 17:07:07 zynthian-v5-64 startx[934]:     self.zynseq.libseq.addNote(step, note, velocity, 1)  # Add short event, may overwrite later when note-off detected
Jun 03 17:07:07 zynthian-v5-64 startx[934]:     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 03 17:07:07 zynthian-v5-64 startx[934]: TypeError: this function takes at least 5 arguments (4 given)
```
