### ISSUE TITLE
Cannot bind to custom switches (using dummies)

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1094]
# Describe the issue
If you add dummy custom buttons by adding `-1` elements to the wiring config then try to bind keys to the extra custom switches, these key bindings fail with an error in the log.
# To Reproduce
## Steps to reproduce the behavior:
1. In webconf, set wiring layout to "Dummies"
2. Set Switches Pins to `-1,-1,-1,-1,-1,-1` and save
3. Use UI Key Binding to bind a key to `	ZYNSWITCH 4` and save 
4. On USB/VNC (QWERTY) keyboard press the bound key
 ## Expected behaviour
Menu is shown.
## Actual behaviour
Nothing happens. Log error:
```
Jun 23 10:09:54 zynthian-rpi5 startx[1057]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: ['4', 'P']
Jun 23 10:09:54 zynthian-rpi5 startx[1057]: Traceback (most recent call last):
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2291, in cuia_thread_task
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:     if self.zynswitch_push(i):
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:        ^^^^^^^^^^^^^^^^^^^^^^
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1824, in zynswitch_push
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:     return self.custom_switch_ui_action(i - 4, "P")
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1661, in custom_switch_ui_action
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:     action_config = zynthian_gui_config.custom_switch_ui_actions[i]
Jun 23 10:09:54 zynthian-rpi5 startx[1057]:                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~^^^
Jun 23 10:09:54 zynthian-rpi5 startx[1057]: IndexError: list index out of range
Jun 23 10:09:57 zynthian-rpi5 startx[1057]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: ['4', 'R']
Jun 23 10:09:57 zynthian-rpi5 startx[1057]: Traceback (most recent call last):
Jun 23 10:09:57 zynthian-rpi5 startx[1057]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2282, in cuia_thread_task
Jun 23 10:09:57 zynthian-rpi5 startx[1057]:     if zynswitch_cuia_ts[i] is None:
Jun 23 10:09:57 zynthian-rpi5 startx[1057]:        ~~~~~~~~~~~~~~~~~^^^
Jun 23 10:09:57 zynthian-rpi5 startx[1057]: IndexError: list index out of range
```
# Additional context
It seems that the number of (custom) switches is being derived from zyncontrol which returns 0 but the quantity configured in webconf is higher. There should be some correlation between the webconf setting and the quantity of switches that zynthian detects / uses.
# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Dummy device
Display: MIPI DSI 800x480
Wiring: DUMMIES
I2C: Not detected
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-05-21
Memory: 7% (576M/8052M)
SD Card: NA (NA/NA)
Temperature: 52.1ºC
Overclock: Medium
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (e0014fe) 
zynthian-ui: oram (72d1aab)
zynthian-sys: oram (943713b)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (2dba270)
```

**Comment by riban-bw** [comment]
Nope! Now all of the keybinding is triggering errors, even switches 1-4 that were previously working.

```
Jun 23 13:50:58 zynthian-rpi5 startx[4200]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: ['0', 'P']
Jun 23 13:50:58 zynthian-rpi5 startx[4200]: Traceback (most recent call last):
Jun 23 13:50:58 zynthian-rpi5 startx[4200]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2294, in cuia_thread_task
Jun 23 13:50:58 zynthian-rpi5 startx[4200]:     zynswitch_cuia_ts[i] = monotonic()
Jun 23 13:50:58 zynthian-rpi5 startx[4200]:     ~~~~~~~~~~~~~~~~~^^^
Jun 23 13:50:58 zynthian-rpi5 startx[4200]: IndexError: list assignment index out of range
^[[IJun 23 13:51:01 zynthian-rpi5 startx[4200]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: ['0', 'R']
Jun 23 13:51:01 zynthian-rpi5 startx[4200]: Traceback (most recent call last):
Jun 23 13:51:01 zynthian-rpi5 startx[4200]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2282, in cuia_thread_task
Jun 23 13:51:01 zynthian-rpi5 startx[4200]:     if zynswitch_cuia_ts[i] is None:
Jun 23 13:51:01 zynthian-rpi5 startx[4200]:        ~~~~~~~~~~~~~~~~~^^^
Jun 23 13:51:01 zynthian-rpi5 startx[4200]: IndexError: list index out of range
```

Even clicking the topbar gives an error now!!!

**Comment by riban-bw** [comment]
Now fixed, thanks.
