### ISSUE TITLE
Touch stops working

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1102]
# Describe the issue
The touch interface sometimes stops working.
# To Reproduce
## Steps to reproduce the behavior:
Not sure - it is broken when I try to use it...
# Additional context
Log:
```
Jun 28 09:04:30 zynthian startx[1090]: Exception in thread Multitouch:
Jun 28 09:04:30 zynthian startx[1090]: Traceback (most recent call last):
Jun 28 09:04:30 zynthian startx[1090]:   File "/usr/lib/python3.11/threading.py", line 1038, in _bootstrap_inner
Jun 28 09:04:30 zynthian startx[1090]:     self.run()
Jun 28 09:04:30 zynthian startx[1090]:   File "/usr/lib/python3.11/threading.py", line 975, in run
Jun 28 09:04:30 zynthian startx[1090]:     self._target(*self._args, **self._kwargs)
Jun 28 09:04:30 zynthian startx[1090]:   File "/zynthian/zynthian-ui/zyngui/multitouch.py", line 249, in _run
Jun 28 09:04:30 zynthian startx[1090]:     self._process_evdev_events()
Jun 28 09:04:30 zynthian startx[1090]:   File "/zynthian/zynthian-ui/zyngui/multitouch.py", line 275, in _process_evdev_events
Jun 28 09:04:30 zynthian startx[1090]:     self._process_touch_events()
Jun 28 09:04:30 zynthian startx[1090]:   File "/zynthian/zynthian-ui/zyngui/multitouch.py", line 354, in _process_touch_events
Jun 28 09:04:30 zynthian startx[1090]:     ev_handler.function(event)
Jun 28 09:04:30 zynthian startx[1090]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 598, in on_fader_motion
Jun 28 09:04:30 zynthian startx[1090]:     self.set_volume(self.zctrls['level'].value + (self.touch_y - event.y) / self.fader_height)
Jun 28 09:04:30 zynthian startx[1090]:                                                   ^^^^^^^^^^^^
Jun 28 09:04:30 zynthian startx[1090]: AttributeError: 'zynthian_gui_mixer_strip' object has no attribute 'touch_y'
```
# Configuration
## Hardware
```
Raspberry Pi 5 Model B Rev 1.0
Audio: Dummy device
Display: MIPI DSI 800x480
Wiring: DUMMIES
I2C: Not detected
Profile: 
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-06-25
Memory: 15% (1259M/8052M)
SD Card: 99% (13G/14G)
Temperature: 48.3ºC
Overclock: None
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 60 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (628f3fb) 
zynthian-ui: oram (371f6df)
zynthian-sys: oram (4461148)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by riban-bw** [comment]
This is probably caused by touching when screen is off then dragging. The initial touch wakes the screen but does not set the y value. We may prefer to avoid doing anything until y is set, e.g. unset y on release.
