### ISSUE TITLE
After adding a new LV2 plugin, it fails to load into a chain

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1107]
# Describe the issue
If you install a new LV2 plugin then run "Search for Engines" in webconf and enable the newly found plugin in webconf, then when you try to add it to a chain, an error occurs and Zynthian locks up.
# To Reproduce
## Steps to reproduce the behavior:
1. Install a new LV2 plugin, e.g. `make install` for [brummer10 Impulse Loader](https://github.com/brummer10/ImpulseLoader.lv2)
2. In webconf SOFTWARE->Engine, "Search for Engines"
3. Enable the new plugin in webconf
4. In Zynthian UI, add a chain then add the new plugin
 ## Expected behaviour
Plugin is added.
## Actual behaviour
Zynthian freezes with errors in log.
# Screenshots
# Additional context
Log:
```
Jul 01 15:32:59 zynthian-v5-64 startx[3928]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: ['1', 'R']
Jul 01 15:32:59 zynthian-v5-64 startx[3928]: Traceback (most recent call last):
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2310, in cuia_thread_task
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     self.zynswitch_short(i)
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1917, in zynswitch_short
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     self.back_screen()
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 658, in back_screen
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     self.close_screen()
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 646, in close_screen
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     self.show_screen(last_screen)
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 586, in show_screen
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     if not self.screens[screen].build_view():
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_chain_options.py", line 188, in build_view
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     super().build_view()
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 162, in build_view
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     self.fill_list()
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_chain_options.py", line 101, in fill_list
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     self.list_data += self.generate_chaintree_menu()
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_chain_options.py", line 153, in generate_chaintree_menu
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:     res.append((self.processor_options, processor, "  " * indent + "┗━ " + name))
Jul 01 15:32:59 zynthian-v5-64 startx[3928]:                                                    ~~~~~~~~~~~~~~~~~~~~~~^~~~~~
Jul 01 15:32:59 zynthian-v5-64 startx[3928]: TypeError: can only concatenate str (not "NoneType") to str
```
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 16% (632M/3792M)
SD Card: 95% (26G/29G)
Temperature: 51.1ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (628f3fb) 
zynthian-ui: oram (99bfb37)
zynthian-sys: oram (4461148)
zynthian-data: oram (e222e11)
zynthian-webconf: oram (f31699f)
```

**Comment by riban-bw** [comment]
There seems to be an issue with setting all the modules configurations and a reboot is often required.

**Comment by riban-bw** [comment]
This is even more relevant now that we have a simple way to install LV2 plugins.

I think the issue is that webconf has its own instance of zynthian_lv2 to zynthian ui and the ui does not reinitialise its world. Maybe there can be a check of the cache file for a change.

**Comment by riban-bw** [comment]
Simple fix - just re-init lilv if cache has changed.
