### ISSUE TITLE
Backup via web inteface 'crashes' when a symbolic link is being copied that contains a link to a file that does not exist. It gives a '500: Internal Server Error'

### ISSUE THREAD

**Issue by maarthome** [zynthian/zynthian-issue-tracking#1136]
**Describe the bug**
Backup via web interface 'crashes' when a symbolic link is being copied that contains a link to a file that does not exist. It gives a '500: Internal Server Error'
When I modify the symbolic link such that it points to an existing file the backup is OK.

**To Reproduce**
1. http://zynthian.local/sys-backup
2. Click on 'Backup' button
3. All goes well until it try to copy the symbolic link that references to a file that does not exist. 
4. (When I correct the link to point to a existing file is all goes well)

**Expected behavior**
Backup the link itself and not the file that is points at. In this way redundancy is avoided when restoring the backup. It would write real files to the locations where the links were located.

**Screenshots**
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: /zynthian/zynthian-my-data/presets/mod-ui/pedalboards/MDin_Git_Voc_2_4.pedalboard
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: thumbnail.png
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: MDin_Git_Voc_2_4.ttl
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: addressings.json
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: snapshots.json
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: screenshot.png
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: manifest.ttl
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: /zynthian/zynthian-my-data/presets/mod-ui/pedalboards/MDin_Git_Voc_2_4.pedalboard/effect-9
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: effect.ttl
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: INFO:system_backup_handler.zip_backup_items: Fender Twin Reverb TS808 g-11 di half .json
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: ERROR:web.log_exception: Uncaught exception POST /sys-backup (192.168.1.181)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: HTTPServerRequest(protocol='http', host='zynthian.local', method='POST', uri='/sys-backup', version='HTTP/1.1', remote_ip='192.168.1.181')
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: Traceback (most recent call last):
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     result = method(*self.path_args, **self.path_kwargs)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 3301, in wrapper
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     return method(self, *args, **kwargs)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/zynthian-webconf/lib/system_backup_handler.py", line 121, in post
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     errors = {
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:              ^
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/zynthian-webconf/lib/system_backup_handler.py", line 123, in <lambda>
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     'BACKUP_ALL': lambda: self.do_backup_all(),
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:                           ^^^^^^^^^^^^^^^^^^^^
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/zynthian-webconf/lib/system_backup_handler.py", line 154, in do_backup_all
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     self.do_backup('zynthian_backup', backup_items)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/zynthian-webconf/lib/system_backup_handler.py", line 177, in do_backup
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     self.walk_backup_items(zip_backup_items, backup_items)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/zynthian-webconf/lib/system_backup_handler.py", line 192, in walk_backup_items
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     worker(dirname, subdirs, files)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/zynthian/zynthian-webconf/lib/system_backup_handler.py", line 175, in zip_backup_items
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     zf.write(os.path.join(dirname, filename))
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/usr/lib/python3.11/zipfile.py", line 1783, in write
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     zinfo = ZipInfo.from_file(filename, arcname,
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:   File "/usr/lib/python3.11/zipfile.py", line 530, in from_file
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:     st = os.stat(filename)
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]:          ^^^^^^^^^^^^^^^^^
Jul 31 14:10:20 zynthian zynthian_webconf.sh[935]: FileNotFoundError: [Errno 2] No such file or directory: '/zynthian/zynthian-my-data/presets/mod-ui/pedalboards/MDin_Git_Voc_2_4.pedalboard/effect-9/Fender Twin Reverb TS808 g-11 di half .json'

**Setup:**
zyncoder: [oram (62626a8)](https://github.com/zynthian/zyncoder/commit/62626a81147add277cc772fa6770df39e6efb2cc)
zynthian-ui: [oram (3fdc524)](https://github.com/zynthian/zynthian-ui/commit/3fdc524d28bd0927b08fa676aa150977c068a5a0)
zynthian-sys: [oram (5affa51)](https://github.com/zynthian/zynthian-sys/commit/5affa51d7e8dce2764bd4c5f0c3de800d9928cc2)
zynthian-data: [oram (e222e11)](https://github.com/zynthian/zynthian-data/commit/e222e116a1967e38075a96e2bf25aa051f796d30)
zynthian-webconf: [oram (944a957)](https://github.com/zynthian/zynthian-webconf/commit/944a9576ac70e14ce56c6e03d460c15ea0973b16)

PI5 with USB audio card

**Additional context**

**Comment by pianissimo-dev** [comment]
Maybe it's the same cause in my setup. When I try to save a complete bank, web interface crashes with 500 message:
![grafik](https://github.com/user-attachments/assets/0fc2e0c6-e109-4451-9eb0-b254e78997f9)
But I can backup single programs within a bank without a crash:
![grafik](https://github.com/user-attachments/assets/64ed4f76-4e8f-4598-8716-1feac5a9c89a)

I am also on oram, using the latest stable release on V5.1 kit (Pi5, 8GB)
