### ISSUE TITLE
ORAM: Zynthian is unresponsive when accessing sequencer with certain snapshot loaded

### ISSUE THREAD

**Issue by pft** [zynthian/zynthian-issue-tracking#1159]
Zynthian ui locks up when accessing the sequencer with a certain snapshot loaded.

**To Reproduce**
1. Load [016-new-snapshot.zss.json](https://github.com/user-attachments/files/16716853/016-new-snapshot.zss.json)
2. Open the sequencer via the menu

**Expected behavior**
No lock-up

**Screenshots**

 - Software Version: Zynthian v4, on Oram.

**Additional context**
It seems the snapshot is faulty. I do manage to load the sequencer via Akai APC key 25 mk2 (with which I also created this snapshot/sequences) but there it hangs after certain scenes (1 and 4), which look mighty tiny. Scene 6 is OK. I can provide a photograph if needed.

** Log of the normal way (zynthian-only).**

```
Aug 22 20:01:18 zynthian startx[3588]: Building XImage...done
Aug 22 20:01:19 zynthian startx[3589]: ZynCore: Configured 8 x Logical Zynswitches...
Aug 22 20:01:19 zynthian startx[3589]: ZynCore: Setting-up 8 x Physical Zynswitches...
Aug 22 20:01:19 zynthian startx[3589]: ZynCore: Setting-up 4 x Zynpots (zyncoders)...
Aug 22 20:01:19 zynthian startx[3589]: ZynCore->gpiod_start_callbacks: Callback thread created successfully
Aug 22 20:01:22 zynthian startx[3589]: Started libzynaudioplayer using libsndfile-1.2.0
Aug 22 20:01:22 zynthian startx[3589]: Started libzynmixer
Aug 22 20:01:22 zynthian startx[3589]: Started libzynseq
Aug 22 20:01:22 zynthian startx[3589]: Started libzynsmf
Aug 22 20:01:23 zynthian startx[3589]: WARNING:zynthian_gui_brightness_config.init_ctrls: Can't set display brightness!
Aug 22 20:04:29 zynthian startx[3589]: ERROR:zynthian_gui.cuia_thread_task: CUIA 'zynswitch' failed with params: (3, 'S')
Aug 22 20:04:29 zynthian startx[3589]: Traceback (most recent call last):
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2335, in cuia_thread_task
Aug 22 20:04:29 zynthian startx[3589]: self.zynswitch_short(i)
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1948, in zynswitch_short
Aug 22 20:04:29 zynthian startx[3589]: self.screens[self.current_screen].switch_select('S')
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 346, in switch_select
Aug 22 20:04:29 zynthian startx[3589]: self.click_listbox(None, t)
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 337, in click_listbox
Aug 22 20:04:29 zynthian startx[3589]: self.select_action(self.index, t)
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_main_menu.py", line 79, in select_action
Aug 22 20:04:29 zynthian startx[3589]: self.last_action(t)
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_main_menu.py", line 126, in step_sequencer
Aug 22 20:04:29 zynthian startx[3589]: self.zyngui.show_screen('zynpad')
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 585, in show_screen
Aug 22 20:04:29 zynthian startx[3589]: if not self.screens[screen].build_view():
Aug 22 20:04:29 zynthian startx[3589]: ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zynpad.py", line 111, in build_view
Aug 22 20:04:29 zynthian startx[3589]: self.refresh_status(True)
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zynpad.py", line 549, in refresh_status
Aug 22 20:04:29 zynthian startx[3589]: self.update_grid()
Aug 22 20:04:29 zynthian startx[3589]: File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zynpad.py", line 247, in update_grid
Aug 22 20:04:29 zynthian startx[3589]: self.grid_canvas.itemconfig(self.pads[pad]["group"], font=(zynthian_gui_config.font_family, fs2))
Aug 22 20:04:29 zynthian startx[3589]: ~~~~~~~~~^^^^^
Aug 22 20:04:29 zynthian startx[3589]: IndexError: list index out of range 
```

```

**Comment by pft** [comment]
![IMG_20240822_214523](https://github.com/user-attachments/assets/ac987dee-f070-48e7-a0e8-a3fa81e757fc)

A screenshot of the tiny sequencer scenes

**Comment by jofemodo** [comment]
What is the origin of this snapshot? Is it imported from a previous version or is it generated from scratch with oram?

**Comment by pft** [comment]
It was created from scratch using oram.

**Comment by jofemodo** [comment]
OK! It's solved now. I will ask Oscar to limit the number of sequences per bank to 64.

**Comment by pft** [comment]
Thank you, I just tested it and it works!

**Comment by oscaracena** [comment]
I think the problem arises when you create a new scene. Surely, its now fixed on `zynpad.py`, but I'll check why it creates a so big new scene...

**Comment by oscaracena** [comment]
I thought that I create the bank (scene) when it does not exists, but the code on SCENE change is this:

```python
if self._track_buttons_function == FN_SCENE:
    self._zynseq.select_bank(index + 1)
    self._state_manager.send_cuia("SCREEN_ZYNPAD")
    return True
```

It just selects the bank and opens the ZynPad. As the problem is fixed in zynpad.py, I think there is no need for anything else 😉
