### ISSUE TITLE
Issue: Cannot save Snapshot. When I assign (in the zynthian interface, so not in the MOD web browser) the bypass of an lv2 effect (MOD-UI) to a controller , I cannot SAVE the snapshot

### ISSUE THREAD

**Issue by maarthome** [zynthian/zynthian-issue-tracking#1200]
# Describe the issue
When I assign (in the zynthian interface, so not in the MOD web browser) the bypass of an lv2 effect (MOD-UI) to a controller , I cannot SAVE the snapshot…

# Configuration

Raspberry Pi 5 Model B Rev 1.0
Audio: Generic USB device
Display: MPI5008 800x480
Wiring: CUSTOM
I2C: Not detected
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-09-11
Memory: 23% (934M/4045M)
SD Card: 13% (14G/114G)
Temperature: 57.6ºC
Overclock: Maximum
USB/ZynthianRec: 2% (630M/59G)
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: On
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (51ab3c7) 
zynthian-ui: v5touch (86b58af)
zynthian-sys: oram (6d4fed7)
zynthian-data: oram (6fa0db4)
zynthian-webconf: oram (8c261ba)
```

**Comment by maarthome** [comment]
The error message:

Sep 18 16:09:52 zynthian startx[1116]: ERROR:zynthian_state_manager.save_snapshot: Traceback (most recent call last):
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 954, in save_snapshot
Sep 18 16:09:52 zynthian startx[1116]:     state = self.get_state()
Sep 18 16:09:52 zynthian startx[1116]:             ^^^^^^^^^^^^^^^^
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 906, in get_state
Sep 18 16:09:52 zynthian startx[1116]:     self.save_zs3("zs3-0", "Last state")
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 1420, in save_zs3
Sep 18 16:09:52 zynthian startx[1116]:     mcstate = self.get_midi_capture_state()
Sep 18 16:09:52 zynthian startx[1116]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 1622, in get_midi_capture_state
Sep 18 16:09:52 zynthian startx[1116]:     mcstate[uid]["midi_cc"][chan_cc].append([zctrl.processor.id, zctrl.symbol])
Sep 18 16:09:52 zynthian startx[1116]:                                              ^^^^^^^^^^^^^^^^^^
Sep 18 16:09:52 zynthian startx[1116]: AttributeError: 'NoneType' object has no attribute 'id'
Sep 18 16:09:52 zynthian startx[1116]: Traceback (most recent call last):
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 954, in save_snapshot
Sep 18 16:09:52 zynthian startx[1116]:     state = self.get_state()
Sep 18 16:09:52 zynthian startx[1116]:             ^^^^^^^^^^^^^^^^
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 906, in get_state
Sep 18 16:09:52 zynthian startx[1116]:     self.save_zs3("zs3-0", "Last state")
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 1420, in save_zs3
Sep 18 16:09:52 zynthian startx[1116]:     mcstate = self.get_midi_capture_state()
Sep 18 16:09:52 zynthian startx[1116]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Sep 18 16:09:52 zynthian startx[1116]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 1622, in get_midi_capture_state
Sep 18 16:09:52 zynthian startx[1116]:     mcstate[uid]["midi_cc"][chan_cc].append([zctrl.processor.id, zctrl.symbol])
Sep 18 16:09:52 zynthian startx[1116]:                                              ^^^^^^^^^^^^^^^^^^
Sep 18 16:09:52 zynthian startx[1116]: AttributeError: 'NoneType' object has no attribute 'id'
Sep 18 16:09:52 zynthian startx[1116]: ERROR:zynthian_state_manager.save_snapshot: Can't save snapshot file '/zynthian/zynthian-my-data/snapshots/000/023-try3.zss': 'NoneType' object has no attribute 'id'
