### ISSUE TITLE
Error accessing pattern editor

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1221]
# Describe the issue
On a V5 showing ZynPad, pressing the PAD/STEP button, there was an error on the screen and navigation failed.

# To Reproduce
## Steps to reproduce the behavior:
1. ZynPad
2. Press PAD/STEP
 ## Expected behaviour
Pattern editor shows.
## Actual behaviour
Error message.
# Additional context
Log:
```
Oct 02 19:29:15 zynthian-v5-64 startx[926]: ERROR:zynthian_gui.cuia_thread_task: CUIA 'zynswitch' failed with params: (>
Oct 02 19:29:15 zynthian-v5-64 startx[926]: Traceback (most recent call last):
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2385, in cuia_t>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     self.zynswitch_short(i)
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2008, in zynswi>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     return self.custom_switch_ui_action(i - 4, "S")
Oct 02 19:29:15 zynthian-v5-64 startx[926]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1724, in custom>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     self.callable_ui_action_params(cuia)
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1048, in callab>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     self.callable_ui_action(cuia, params)
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1034, in callab>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     cuia_func(params)
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1339, in cuia_s>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     success = self.screens[self.current_screen].show_pattern_editor()
Oct 02 19:29:15 zynthian-v5-64 startx[926]:               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_zynpad.py", line 529, in >
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     self.zyngui.screens['pattern_editor'].load_pattern(pattern)
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 1>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     self.select_cell()
Oct 02 19:29:15 zynthian-v5-64 startx[926]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 1>
Oct 02 19:29:15 zynthian-v5-64 startx[926]:     note = self.keymap[row]['note']
Oct 02 19:29:15 zynthian-v5-64 startx[926]:            ~~~~~~~~~~~^^^^^
Oct 02 19:29:15 zynthian-v5-64 startx[926]: TypeError: list indices must be integers or slices, not float
```
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 18% (707M/3792M)
SD Card: 96% (26G/29G)
Temperature: 53.0ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: oram (71de6d2) 
zynthian-ui: oram (f43f293)
zynthian-sys: oram (a717e49)
zynthian-data: oram (ddfa009)
zynthian-webconf: oram (b530397)
```

**Comment by riban-bw** [comment]
This is likely to be caused by:
```
        self.base_row_height = self.grid_height / DEFAULT_VIEW_ROWS
        self.base_step_width = self.grid_width / DEFAULT_VIEW_STEPS
```
in zynthian_gui_patterneditor.py. The fix will be to replace with:
```
        self.base_row_height = self.grid_height // DEFAULT_VIEW_ROWS
        self.base_step_width = self.grid_width // DEFAULT_VIEW_STEPS
```

I will do this when the coding style refactor change freeze ends.

**Comment by riban-bw** [comment]
Fixed in Vangelis (testing). Ready to be deployed in next point release.
