### ISSUE TITLE
Error in mixer learn

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#1240]
# Describe the issue
Pressing the wrong buttons during mixer learn triggers an error.
# To Reproduce
## Steps to reproduce the behavior:
1. Enter mixer learn, e.g. V4 short press learn.
2. Short press SELECT.
 ## Expected behaviour
No error.
## Actual behaviour
Error.
# Additional context
```
ERROR:zynthian_gui.cuia_thread_task: CUIA 'zynswitch' failed with params: ['3', 'R']
Traceback (most recent call last):
  File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2394, in cuia_thread_task
    self.zynswitch_short(i)
  File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1995, in zynswitch_short
    if self.screens[self.current_screen].switch(i, 'S'):
       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 1046, in switch
    return self.switch_select(t)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/zynthian-ui/zyngui/zynthian_gui_mixer.py", line 987, in switch_select
    self.zynmixer.midi_learn_zctrl_menu(self.zynmixer.midi_learn_zctrl)
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AttributeError: 'zynmixer' object has no attribute 'midi_learn_zctrl_menu'
```
# Configuration
## Hardware
```
Raspberry Pi 4 Model B Rev 1.5
Audio: V5 ADAC
Display: MIPI DSI 800x480 (inverted)
Wiring: V5
I2C: MCP23017@0x20, MCP23017@0x21
Profile: v5
```
## System
```
Debian GNU/Linux 12 (bookworm)
Build Date: 2024-02-01
Memory: 44% (1677M/3791M)
SD Card: 97% (27G/29G)
Temperature: 50.6ºC
Overclock: Maximum
```
## MIDI & UI
```
Tuning: 440 Hz
Master Channel: Off
Preload Presets: Off
ZS3 (SubSnapShots): On
Power Save: 10 minutes
Audio Levels on Snapshots: On
```
## Software
```
zyncoder: vangelis (1dd6f7a) 
zynthian-ui: vangelis (b2eaca7)
zynthian-sys: vangelis (f842566)
zynthian-data: vangelis (ddfa009)
zynthian-webconf: vangelis (bd99d05)
```

**Comment by riban-bw** [comment]
Corrected call to show context menu. Validated as fixed. Ready for release in next point release.
