### ISSUE TITLE
BACK operation from main screen causes device to become unresponsive

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#178]
**Describe the bug**
BACK operation from main screen will clear the text from the screen, leaving the grey box shading. Further user interaction is unavailable requiring a reboot.

**To Reproduce**
Steps to reproduce the behaviour:
1. Navigate to main screen
2. Click on title bar or press BACK button

**Expected behaviour**
BACK button behaviour is triggered.

**Expected behaviour**
Text is cleared. UI becomes unresponsive to touch / click and encoder / button presses.

**Setup:**
 HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Soundcard: HifiBerry DAC+ light
Display: WaveShare 7 HDMI+USB
Wiring: I2C_HWC
GPIO Expander: Not detected

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-04-09

SOFTWARE
zyncoder: min_value (afb0dbb)
zynthian-ui: master (926af8e)
zynthian-sys: master (04e4dec)
zynthian-data: master (9cccef5)
zynthian-webconf: master (ab294aa)

**Additional context**
The workflow triggers the exception:
```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 669, in cb_keybinding
    self.zyngui.callable_ui_action(action)
  File "./zynthian_gui.py", line 678, in callable_ui_action
    self.zynswitch_short(1)
  File "./zynthian_gui.py", line 922, in zynswitch_short
    self.show_screen(screen_back)
  File "./zynthian_gui.py", line 385, in show_screen
    self.screens[screen].show()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 73, in show
    super().show()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 218, in show
    self.fill_list()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_control.py", line 95, in fill_list
    for cscr in layer.get_ctrl_screens():
AttributeError: 'NoneType' object has no attribute 'get_ctrl_screens'
```

**Comment by jofemodo** [comment]
It's fixed on https://github.com/zynthian/zynthian-ui/issues/228.
