### ISSUE TITLE
Wifi not working out of the box.

### ISSUE THREAD

**Issue by seclorum** [zynthian/zynthian-issue-tracking#308]
**Describe the bug**
Wifi doesn't work out of the box.

**To Reproduce**

Write 2020-09-05-zynthianos-buster-lite-armhf-1.0.0.img to an SD card, put it in the Zynthian, wait for it to resize partitions.  System boots up fine - try to enable Wifi - message returns, "Cannot configure Wifi device".

Enable Wifi Hotspot, connect to Zynthian wifi hotspot, configure Zynthian to join home Wifi, disable hotspot, reboot - enable Wifi.  Still no dice, Zynthian doesn't connect, isn't accessible over Wifi.  Enable Hotspot though: its accessible.

No matter what I do I cannot get the Zynthian to join a Wifi - have verified and double-checked passwords, etc. a thousand times, they are correct for sure.

**Expected behavior**
Out of the box I should be able to enable Wifi and connect to my studio WLAN, no?

**Setup:**
 - SD-image: 2020-09-05-zynthianos-buster-lite-armhf-1.0.0.img
 - Hardware Config: V4 official kit

**Additional context**
Discussed here:

https://discourse.zynthian.org/t/wifi-not-working-out-of-the-box/5361/9

**Comment by seclorum** [comment]
To add - after flashing the image and booting it, I then also did the "Update" menu option, and it looked to me like the Zynthian updated itself after a few minutes..

**Comment by jofemodo** [comment]
Have you configured your WIFI networks from the webconf tool? You have to do this before WIFI can work. You can do this from the Zynthian UI.
If you want to configure your zynthian starting from a fresh image without using a network cable, then you should use the WIFI Hotspot feature, that can be enabled from the Zynthian UI.

**Comment by jofemodo** [comment]
How many different WLans have you tried with? I regularly have configured several ones and have no problems with it. I can't reproduce your problem. I would need more info ...

**Comment by jaylfc** [comment]
Same here, was working on a previous install but cant remember what version. Had to borrow the sd card and after reflashing it with latest wifi is a no go.

**Comment by jaylfc** [comment]
Managed to get it working by adding my SSID and pass, save, enable hotspot, save, switch to on and save again.

**Comment by riban-bw** [comment]
Oram is suffering an issue with enabling wifi. Log:

```
Feb 24 17:29:56 zynthian-v5-64 startx[19791]: /bin/sh: 1: /zynthian/zynthian-sys/sbin/set_wifi.sh: not found
Feb 24 17:29:56 zynthian-v5-64 startx[18485]: ERROR:zynthian_gui.cuia_thread_task: CUIA zynswitch failed with params: (3, 'S')
Feb 24 17:29:56 zynthian-v5-64 startx[18485]: Traceback (most recent call last):
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 2235, in cuia_thread_task
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     self.zynswitch_short(i)
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui.py", line 1861, in zynswitch_short
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     self.screens[self.current_screen].switch_select('S')
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 340, in switch_select
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     self.click_listbox(None, t)
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_selector.py", line 334, in click_listbox
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     self.select_action(self.index, t)
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zyngui/zynthian_gui_admin.py", line 184, in select_action
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     self.last_action()
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zyngine/zynthian_state_manager.py", line 1791, in start_wifi
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     if not zynconf.start_wifi():
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:            ^^^^^^^^^^^^^^^^^^^^
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/zynthian/zynthian-ui/zynconf/zynthian_config.py", line 390, in start_wifi
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     check_output(sys_dir + "/sbin/set_wifi.sh on", shell=True)
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/usr/lib/python3.11/subprocess.py", line 466, in check_output
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:   File "/usr/lib/python3.11/subprocess.py", line 571, in run
Feb 24 17:29:56 zynthian-v5-64 startx[18485]:     raise CalledProcessError(retcode, process.args,
Feb 24 17:29:56 zynthian-v5-64 startx[18485]: subprocess.CalledProcessError: Command '/zynthian/zynthian-sys/sbin/set_wifi.sh on' returned non-zero exit status 127.
```

**Comment by riban-bw** [comment]
The issue I describe above seems to now be unused. We should remove the obsolete wifi code from state manager (start_wifi, stop_wifi, etc.).
We should also move the wifi control code from the GUI page to state manager. This is core functionality and should not be in GUI. The wifi GUI page should call the state manager function.
None of the original reporters of this bug have updated since the changes to wifi manager were implemented. Will @seclorum & @jaylfc please confirm whether wifi now works as expected?

**Comment by jofemodo** [comment]
I just removed the deprecated code from state manager.
Regarding the current wifi code, the more complex functions are in zynconf. For the rest, it's not easy to move out from the GUI because "nmcli" is indeed a UI, so it fits nicely the GUI needs. Creating another layer in the state manager would be very redundant and useless. Think it's quite similar to what you do with bluetoothctl in the BLE GUI. It has no sense to create another wrapper.

**Comment by riban-bw** [comment]
The code to scan for new BLE devices is in the GUI but the code to enable and disable Bluetooth is in state manager. I think we should have similar - ability to enable / disable the service in state manager (hence available via a future API) but scanning done via UI.
