### ISSUE TITLE
UI locks up whilst removing layer

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#387]
**Describe the bug**
Sometimes the UI gets stuck at "Do you really want to remove this layer? - No / Yes".

**To Reproduce**
1. CLEAN ALL
2. New Synth Layer, FS, CH1,, AVL Drunkits Perc
3. New Synth Layer, Dexed, CH2,, DCDCollection, 01_FM-Rhodes
4. New Audio-FX Layer, ZynChorus, CH3, Celeste 1
5. In Layers menu bold press on layer 3 and select Remove Layer
6. Press SELECT for Yes

**Expected behaviour**
Pressing No or Yes closes the confirmation dialog and returns to Layer list.

**Actual behaviour**
Pressing No or Yes does nothing.

**Setup:**
HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-05-27
Memory: 17% (165M/926M)
SD Card: 40% (11G/29G)
Temperature: 53.2ºC

SOFTWARE
zyncoder: code_review (dcb627e)
zynthian-ui: sprint_2021.02.27 (ac7e976)
zynthian-sys: master (6d93662)
zynthian-data: master (194fd59)
zynthian-webconf: master (45bcb08)

**Additional context**
Log shows:

```
Exception in Tkinter callback
Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "./zynthian_gui.py", line 1832, in cb_keybinding
    zyngui.callable_ui_action(action)
  File "./zynthian_gui.py", line 813, in callable_ui_action
    self.zynswitch_short(3)
  File "./zynthian_gui.py", line 1140, in zynswitch_short
    self.screens[self.modal_screen].switch_select('S')
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_confirm.py", line 120, in switch_select
    self.zyngui.close_modal()
  File "./zynthian_gui.py", line 465, in close_modal
    self.show_modal(self.modal_screen_back)
  File "./zynthian_gui.py", line 458, in show_modal
    self.screens[screen].show()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer_options.py", line 178, in show
    super().show()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 126, in show
    self.fill_list()
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer_options.py", line 91, in fill_list
    self.layer = self.zyngui.screens['layer'].root_layers[self.layer_index]
IndexError: list index out of range
```

**Comment by riban-bw** [comment]
Just merged master into branch and this issue has disappeared.
