### ISSUE TITLE
2021-03-19 image not building zynthian libraries

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#410]
**Describe the bug**
Image 2021-03-19 _should_ be a version of the current stable build and hence we should be able to use it as the new stable image but it fails to start because libraries are not being built.

**To Reproduce**
1. Download and flash 2021-03-19 image
2. Boot Zynthian and wait for reboot

**Expected behaviour**
Zynthian boots into UI.

**Actual behaviour**
Zynthian shows error screen.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23008

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-03-19
Memory: 6% (135M/1939M)
SD Card: 89% (9.2G/11G)
Temperature: 44.3ºC

SOFTWARE
zyncoder: stable (d852c8f)
zynthian-ui: stable (6cdb0ad)
zynthian-sys: master (140eac7)
zynthian-data: stable (194fd59)
zynthian-webconf: stable (b64c737)

**Additional context**
This was a fresh install on a standard V4.1 hardware kit. Extract from log:
```
Mar 21 22:05:42 zynthian startx[493]:   Building XImage...done
Mar 21 22:05:48 zynthian startx[493]: ERROR:zynthian_gui.__init__: ERROR initializing jackpeak: 'NoneType' object has no attribute 'setDecay'
Mar 21 22:05:48 zynthian startx[493]: ERROR:zynthian_gui.__init__: ERROR initializing Controllers & MIDI-router: 'NoneType' object has no attribute 'setup_zynswitch_midi'
Mar 21 22:05:48 zynthian startx[493]: Can't initialise zynseq library: /home/pi/zynthian-ui/zynlibs/zynseq/build/libzynseq.so: cannot open shared object file: No such file or directory
Mar 21 22:05:48 zynthian startx[493]: Can't initialise zynsmf library: /home/pi/zynthian-ui/zynlibs/zynsmf/build/libzynsmf.so: cannot open shared object file: No such file or directory
Mar 21 22:05:48 zynthian startx[493]: Can't init jackpeak library: /home/pi/zynthian-ui/zynlibs/jackpeak/build/libjackpeak.so: cannot open shared object file: No such file or directory
Mar 21 22:05:48 zynthian startx[493]: Can't init zyncoder library: /home/pi/zyncoder/build/libzyncoder.so: cannot open shared object file: No such file or directory
Mar 21 22:05:48 zynthian startx[493]: Traceback (most recent call last):
Mar 21 22:05:48 zynthian startx[493]:   File "./zynthian_gui.py", line 1747, in <module>
Mar 21 22:05:48 zynthian startx[493]:     zynthian_gui_config.zyngui=zyngui=zynthian_gui()
Mar 21 22:05:48 zynthian startx[493]:   File "./zynthian_gui.py", line 223, in __init__
Mar 21 22:05:48 zynthian startx[493]:     self.libseq = CDLL("/zynthian/zynthian-ui/zynlibs/zynseq/build/libzynseq.so")
Mar 21 22:05:48 zynthian startx[493]:   File "/usr/lib/python3.7/ctypes/__init__.py", line 356, in __init__
Mar 21 22:05:48 zynthian startx[493]:     self._handle = _dlopen(self._name, mode)
Mar 21 22:05:48 zynthian startx[493]: OSError: /zynthian/zynthian-ui/zynlibs/zynseq/build/libzynseq.so: cannot open shared object file: No such file or directory
Mar 21 22:05:48 zynthian startx[493]:  PNG file: /zynthian/config/img/fb_zynthian_error_ip.png - Application must supply a known background gamma
Mar 21 22:05:48 zynthian startx[493]: /zynthian/config/img/fb_zynthian_error_ip.png is 480x320 PNG image, color type RGB_ALPHA, 8 bit, file gamma 0.4546
Mar 21 22:05:48 zynthian startx[493]:   Zooming image by 100%...done
Mar 21 22:05:48 zynthian startx[493]:   Merging...done
Mar 21 22:05:48 zynthian startx[493]:   Building XImage...done
```

It looks like none of the libraries are being built: zynseq, zyncoder, etc.

**Comment by riban-bw** [comment]
Manual attempt to build zyncoder gives this error:
```
root@zynthian:~# /zynthian/zyncoder/build.sh
/zynthian/zyncoder ~
/zynthian/zyncoder/build /zynthian/zyncoder ~
++ Defined HAVE_WIRINGPI_LIB
++ Defined MCP23017_ENCODERS
++ Defined MCP23017 INTA PIN
++ Defined MCP23017 INTB PIN
++ Using wiringPI
-- Configuring done
-- Generating done
-- Build files have been written to: /zynthian/zyncoder/build
[ 16%] Linking C shared library libzyncoder.so
/usr/bin/ld: CMakeFiles/zyncoder.dir/zyncoder.c.o: relocation R_ARM_MOVW_ABS_NC against `zyncoder_mcp23017_node' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/zyncoder.dir/zynmidirouter.c.o: relocation R_ARM_MOVW_ABS_NC against `a local symbol' can not be used when making a shared object; recompile with -fPIC
/usr/bin/ld: CMakeFiles/zyncoder.dir/zyncoder.c.o(.text+0x248): unresolvable R_ARM_CALL relocation against symbol `wiringPiSetup'
/usr/bin/ld: final link failed: nonrepresentable section on output
collect2: error: ld returned 1 exit status
make[2]: *** [CMakeFiles/zyncoder.dir/build.make:99: libzyncoder.so] Error 1
make[1]: *** [CMakeFiles/Makefile2:105: CMakeFiles/zyncoder.dir/all] Error 2
make: *** [Makefile:130: all] Error 2
```

**Comment by jofemodo** [comment]
Image 2021-03-19 is a nightly build, not a stable version. A stable version is labelled as "stable", like:

https://os.zynthian.org/2021-03-24-zynthianos-stable-2103.zip

;-)

Regards,
