### ISSUE TITLE
Restart UI - Linux Sampler fails to reloaded

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#475]
**Describe the bug**
Using the UI feature to _Restart UI_ may throw errors in the log, fail to load previous snapshot and trigger xruns.

**To Reproduce**
1. Add Linux Sampler Salamander to Layer 1
2. Add Calf Monosynth to Layer 2
3. From Admin menu, Restart UI

**Expected behaviour**
UI restarts and shows previously loaded engines.

**Actual behaviour**
UI restarts and shows no engines. xruns are occuring regularly.

**Setup:**
HARDWARE
Raspberry Pi 4 Model B Rev 1.4
Soundcard: HifiBerry DAC+ ADC PRO
Display: ZynScreen 3.5 (v1)
Wiring: MCP23017_ZynScreen
GPIO Expander: MCP23017

SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2020-09-05
Memory: 10% (206M/1939M)
SD Card: 38% (11G/29G)
Temperature: 48.0ºC

MIDI
Profile: default.sh
Fine Tuning: 440 Hz
Master Channel: 16
Single Active Channel: off
ZS3 SubSnapShots: on

SOFTWARE
zyncoder: testing (26ffaed)
zynthian-ui: testing (f98d4f7)
zynthian-sys: testing (36e814a)
zynthian-data: testing (315390c)
zynthian-webconf: testing (d09f0ba)

**Additional context**

Repeating after reboot and _Clean All_ gives not errors for loading engines (obviously) but does give continual xruns (which is what I started to investigate) so a restart of UI does trigger a state where xruns are triggered. I wonder if there is a library or other jackd client not being properly unloaded?

Log during restart:
```
Jun 30 09:06:11 zynthian1 startx[484]: libjackpeak registering as 'jackpeak'.
Jun 30 09:06:11 zynthian1 startx[484]: libjackpeak created input ports
Jun 30 09:06:15 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:15 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:17 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(CREATE AUDIO_OUTPUT_DEVICE JACK ACTIVE='true' CHANNELS='16' NAME='LinuxSampler'
Jun 30 09:06:17 zynthian1 startx[484]: ): timed out
Jun 30 09:06:17 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:17 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:18 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(SET AUDIO_OUTPUT_CHANNEL_PARAMETER None 0 NAME='CH0_1'
Jun 30 09:06:18 zynthian1 startx[484]: ): timed out
Jun 30 09:06:19 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(SET AUDIO_OUTPUT_CHANNEL_PARAMETER None 1 NAME='CH0_2'
Jun 30 09:06:19 zynthian1 startx[484]: ): timed out
Jun 30 09:06:19 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:19 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:20 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(SET AUDIO_OUTPUT_CHANNEL_PARAMETER None 2 NAME='CH1_1'
Jun 30 09:06:20 zynthian1 startx[484]: ): timed out
Jun 30 09:06:21 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(SET AUDIO_OUTPUT_CHANNEL_PARAMETER None 3 NAME='CH1_2'
Jun 30 09:06:21 zynthian1 startx[484]: ): timed out
Jun 30 09:06:21 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:21 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:22 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(SET AUDIO_OUTPUT_CHANNEL_PARAMETER None 4 NAME='CH2_1'
Jun 30 09:06:22 zynthian1 startx[484]: ): timed out
Jun 30 09:06:23 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.lscp_send_single: FAILED lscp_send_single(SET AUDIO_OUTPUT_CHANNEL_PARAMETER None 5 NAME='CH2_2'
Jun 30 09:06:23 zynthian1 startx[484]: ): timed out
Jun 30 09:06:23 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:23 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:23 zynthian1 startx[484]: ERROR:zynthian_engine_linuxsampler.ls_init: syntax error, unexpected 'N' (line (ERR 0)
Jun 30 09:06:23 zynthian1 startx[484]: ERROR:zynthian_gui_layer.load_snapshot: Invalid snapshot: syntax error, unexpected 'N' (line (ERR 0)
Jun 30 09:06:23 zynthian1 startx[484]: Traceback (most recent call last):
Jun 30 09:06:23 zynthian1 startx[484]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 1192, in load_snapshot
Jun 30 09:06:23 zynthian1 startx[484]:     self.layers.append(zynthian_layer(engine,lss['midi_chan'], self.zyngui))
Jun 30 09:06:23 zynthian1 startx[484]:   File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 77, in __init__
Jun 30 09:06:23 zynthian1 startx[484]:     self.engine.add_layer(self)
Jun 30 09:06:23 zynthian1 startx[484]:   File "/home/pi/zynthian-ui/zyngine/zynthian_engine_linuxsampler.py", line 225, in add_layer
Jun 30 09:06:23 zynthian1 startx[484]:     self.ls_set_channel(layer)
Jun 30 09:06:23 zynthian1 startx[484]:   File "/home/pi/zynthian-ui/zyngine/zynthian_engine_linuxsampler.py", line 352, in ls_set_channel
Jun 30 09:06:23 zynthian1 startx[484]:     ls_chan_id=self.lscp_send_single("ADD CHANNEL")
Jun 30 09:06:23 zynthian1 startx[484]:   File "/home/pi/zynthian-ui/zyngine/zynthian_engine_linuxsampler.py", line 180, in lscp_send_single
Jun 30 09:06:23 zynthian1 startx[484]:     raise zyngine_lscp_error("{} ({} {})".format(parts[2],parts[0],parts[1]))
Jun 30 09:06:23 zynthian1 startx[484]: zyngine.zynthian_engine_linuxsampler.zyngine_lscp_error: syntax error, unexpected 'N' (line (ERR 0)
Jun 30 09:06:25 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:27 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
Jun 30 09:06:27 zynthian1 startx[484]: WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
```

**Comment by jofemodo** [comment]
It seems a problem with LinuxSampler. Could you reproduce the issue without using LinusSampler?

**Comment by riban-bw** [comment]
Maybe two issues here. The xrun issue is the one that I started to investigate and occurs whether engines are loaded or not so is not specific to Linux Sampler. I have added issue #477 to track the xrun issue.

**Comment by riban-bw** [comment]
I cannot reproduce this with:
```
zyncoder: testing (26ffaed)
zynthian-ui: testing (42d1c47)
zynthian-sys: testing (ca949d9)
zynthian-data: testing (315390c)
zynthian-webconf: testing (38d33ed)
```

I did try to rollback to the _broken_ version and still could not reproduce which worries me that the issue persists but is triggered by a particular configuration. I will close the issue and if it reoccurs we can capture more data on the cause.
