### ISSUE TITLE
Error in log

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#638]
**Describe the bug**
Whilst using Zynthian the log gave an error (see additional context below).

**To Reproduce**
Steps to reproduce the behaviour:
I am showing what I remember I did but it may not be the exact steps to reproduce. Hopefully the errors will show the code issues.
1. With Dexed engine loaded but no preset selected (not sure how that is my default state)
2. Added then removed audio effect

**Expected behavior**
No errors

**Setup:**
- HARDWARE
Raspberry Pi 3 Model B Plus Rev 1.3
Audio: [HifiBerry DAC+ ADC PRO](http://192.168.8.230/hw-audio)
Display: [ZynScreen 3.5 (v1)](http://192.168.8.230/hw-display)
Wiring: [MCP23017_ZynScreen](http://192.168.8.230/hw-wiring)
I2C: [MCP23017@0x20](http://192.168.8.230/hw-wiring)
Profile: [z2_v1](http://192.168.8.230/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2021-09-23
Memory: 44% (415M/923M)
SD Card: 59% (16G/29G)
Temperature: 50.5ºC
Overclock: [Disabled](http://192.168.8.230/hw-options)
- MIDI
Profile: [default.sh](http://192.168.8.230/ui-midi-options)
Tuning: [440 Hz](http://192.168.8.230/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://192.168.8.230/ui-midi-options)
ZS3 Sub-SnapShots: [Off](http://192.168.8.230/ui-midi-options)
MIDI to Output: [On](http://192.168.8.230/ui-midi-options)
Master Channel: [off](http://192.168.8.230/ui-midi-options)
- SOFTWARE
zyncoder: [testing (e236925)](https://github.com/zynthian/zyncoder/commit/e2369251a5456539c8d79e218c8e096accfe0f54)
zynthian-ui: [feature/614_preset_management (930ea81)](https://github.com/zynthian/zynthian-ui/commit/930ea81c51470c7ad76ff157b03848c0ad0ccb1d)
zynthian-sys: [testing (a5e66e4)](https://github.com/zynthian/zynthian-sys/commit/a5e66e4a9119d6ad2504bf78f774fcf33eb4d2fa)
zynthian-data: [testing (10e1f9f)](https://github.com/zynthian/zynthian-data/commit/10e1f9f0e3da196775bda4b8c6fd54a425c3e65c)
zynthian-webconf: [testing (729cc9b)](https://github.com/zynthian/zynthian-webconf/commit/729cc9b4113fd53cea512709028969d389a7d7af)

**Additional context**
```
ERROR:zynthian_gui_layer.add_layer_midich: string index out of range
Exception in Tkinter callback
Traceback (most recent call last):
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 369, in add_layer_midich
    self.layer_control(layer)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 153, in layer_control
    self.zyngui.layer_control(layer)
  File "zynthian_gui.py", line 831, in layer_control
    self.screens['bank'].select_action(0)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_bank.py", line 75, in select_action
    self.zyngui.screens['preset'].select_action(0)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_preset.py", line 63, in select_action
    self.zyngui.curlayer.set_preset(i)
  File "/home/pi/zynthian-ui/zyngine/zynthian_layer.py", line 261, in set_preset
    if preset_name[0]=='❤':
IndexError: string index out of range

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/lib/python3.7/tkinter/__init__.py", line 1705, in __call__
    return self.func(*args)
  File "zynthian_gui.py", line 2181, in cb_keybinding
    zyngui.callable_ui_action(action)
  File "zynthian_gui.py", line 1126, in callable_ui_action
    self.zynswitch_short(3)
  File "zynthian_gui.py", line 1441, in zynswitch_short
    self.screens[self.current_screen].switch_select('S')
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 288, in switch_select
    self.click_listbox(None, t)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 274, in click_listbox
    self.select_action(self.index, t)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_engine.py", line 169, in select_action
    self.zyngui.screens['layer'].add_layer_engine(self.list_data[i][0], self.midi_chan)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 329, in add_layer_engine
    self.add_layer_midich(midi_chan)
  File "/home/pi/zynthian-ui/zyngui/zynthian_gui_layer.py", line 372, in add_layer_midich
    self.zyngui.show_screen('audio_mixer', hmode=SCREEN_HMODE_RESET)
NameError: name 'SCREEN_HMODE_RESET' is not defined
WARNING:zynthian_autoconnect.cb_jack_xrun: Jack Audio XRUN!
```

**Comment by riban-bw** [comment]
Fixed in PR https://github.com/zynthian/zynthian-ui/pull/438.
