### ISSUE TITLE
JX10 caused OverflowError

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#757]
**Describe the bug**
MDA JX10 (modified) caused an OverflowError.

**To Reproduce**
Steps to reproduce the behaviour:
1. Modify JX10 to produce unexpected audio level
2. Play JX10

**Expected behaviour**
Audio level is displayed correctly within limits.

**Actual behaviour**
Audio level meter freezes and error messages shown in log.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.2
Audio: [Z2 ADAC](http://z2/hw-audio)
Display: [Z2 Display](http://z2/hw-display)
Wiring: [Z2_V3](http://z2/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21, ADS1115@0x48, ADS1115@0x49](http://z2/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2022-09-20
Memory: 4% (172M/3838M)
SD Card: 42% (12G/29G)
Temperature: 42.8ºC
Overclock: [Maximum](http://z2/hw-options)
- MIDI
Profile: [default.sh](http://z2/ui-midi-options)
Tuning: [440 Hz](http://z2/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://z2/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://z2/ui-midi-options)
MIDI to Output: [On](http://z2/ui-midi-options)
Master Channel: [16](http://z2/ui-midi-options)
- SOFTWARE
zyncoder: [testing (2dd7230)](https://github.com/zynthian/zyncoder/commit/2dd7230d19ffec787f8d29deab87982bee446303)
zynthian-ui: [testing (13c2b0c)](https://github.com/zynthian/zynthian-ui/commit/13c2b0c85c727457f93d2537f62c7f28f3f08fdc)
zynthian-sys: [testing (0cf1fc6)](https://github.com/zynthian/zynthian-sys/commit/0cf1fc6f8df69c5c5ecad5e6ecbfcb9451dca410)
zynthian-data: [testing (c4c4d3b)](https://github.com/zynthian/zynthian-data/commit/c4c4d3b46e84672c281adf7e7b84d4d3993f5f21)
zynthian-webconf: [testing (f1a3907)](https://github.com/zynthian/zynthian-webconf/commit/f1a39075ec4ee9eda1a4c3d6fac9a12f3f9429d7)

**Additional context**
Log extract:
```
Sep 21 07:44:34 z2 startx[579]: Traceback (most recent call last):
Sep 21 07:44:34 z2 startx[579]:   File "./zynthian_gui.py", line 2176, in refresh_status
Sep 21 07:44:34 z2 startx[579]:     self.screens[self.current_screen].refresh_status(self.status_info)
Sep 21 07:44:34 z2 startx[579]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_base.py", line 457, in refresh_status
Sep 21 07:44:34 z2 startx[579]:     lA = int((max(0, 1 + status['peakA'] / self.dpm_rangedB)) * self.status_l)
Sep 21 07:44:34 z2 startx[579]: OverflowError: cannot convert float infinity to integer
```

This was triggered when I was testing some modifications to JX10 to allow dynamic control of volume. It may be that the audio level is outside expected range which should be handled correctly, not cause this issue.

**Comment by riban-bw** [comment]
I believe this is now resolved by the check for infinty values added to zynmixer.
