### ISSUE TITLE
[Staging-2210] The Sequencer pattern editor grid freeze when we select scale

### ISSUE THREAD

**Issue by TabulaNul** [zynthian/zynthian-issue-tracking#774]
**Describe the bug**
When we quicly select and change scale, the grid pattern editor freezing

**To Reproduce**
1. Go to 'Sequencer'
2. Pattern Editor
3. Select Scale in the Menu
4. Quickly change scale
5. The grid is freezing

**Expected behavior**
the pattern editor grid should not freeze

**Setup:**
 - Staging-2210
 - Zynthian V4

**Comment by riban-bw** [comment]
The following error appears in the log:
```
Oct 13 18:26:25 z2 startx[525]: ERROR:zynthian_gui.refresh_status: list index out of range
Oct 13 18:26:25 z2 startx[525]: Traceback (most recent call last):
Oct 13 18:26:25 z2 startx[525]:   File "./zynthian_gui.py", line 2212, in refresh_status
Oct 13 18:26:25 z2 startx[525]:     self.screens[self.current_screen].refresh_status(self.status_info)
Oct 13 18:26:25 z2 startx[525]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 1028, in refresh_status
Oct 13 18:26:25 z2 startx[525]:     self.draw_grid()
Oct 13 18:26:25 z2 startx[525]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 834, in draw_grid
Oct 13 18:26:25 z2 startx[525]:     self.draw_row(index, colour=="white")
Oct 13 18:26:25 z2 startx[525]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 700, in draw_row
Oct 13 18:26:25 z2 startx[525]:     self.draw_cell(step, row, white)
Oct 13 18:26:25 z2 startx[525]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_patterneditor.py", line 725, in draw_cell
Oct 13 18:26:25 z2 startx[525]:     note = self.keymap[row + self.keymap_offset]["note"]
Oct 13 18:26:25 z2 startx[525]: IndexError: list index out of range
```
