### ISSUE TITLE
Buttons stop working on V5

### ISSUE THREAD

**Issue by riban-bw** [zynthian/zynthian-issue-tracking#898]
**Describe the bug**
After pressing some button combinations the button pad stops working.

**To Reproduce**
Steps to reproduce the behaviour:
1. Press ALT
2. Press REC button
3. Press REC button

**Expected behaviour**
Buttons always work, even if an error has previously occurred.

** Actual behaviour**
Buttons stop working.

**Setup:**
- HARDWARE
Raspberry Pi 4 Model B Rev 1.5
Audio: [V5 ADAC](http://zynthian-v5b/hw-audio)
Display: [MIPI DSI 800x480 (inverted)](http://zynthian-v5b/hw-display)
Wiring: [V5](http://zynthian-v5b/hw-wiring)
I2C: [MCP23017@0x20, MCP23017@0x21](http://zynthian-v5b/hw-wiring)
Profile: [v5](http://zynthian-v5b/hw-wiring)
- SYSTEM
Raspbian GNU/Linux 10 (buster)
Build Date: 2023-06-03
Memory: 7% (280M/3839M)
SD Card: 48% (13G/29G)
Temperature: 48.2ºC
Overclock: [Maximum](http://zynthian-v5b/hw-options)
- MIDI
Profile: [default.sh](http://zynthian-v5b/ui-midi-options)
Tuning: [440 Hz](http://zynthian-v5b/ui-midi-options)
Receive Mode: [Stage (Omni On)](http://zynthian-v5b/ui-midi-options)
ZS3 Sub-SnapShots: [On](http://zynthian-v5b/ui-midi-options)
MIDI to Output: [Off](http://zynthian-v5b/ui-midi-options)
Master Channel: [off](http://zynthian-v5b/ui-midi-options)
- SOFTWARE
zyncoder: [stable (6d54a48)](https://github.com/zynthian/zyncoder/commit/6d54a482e5bd00e3a05e52769045aad6300f1cc0)
zynthian-ui: [stable (67b6afa)](https://github.com/zynthian/zynthian-ui/commit/67b6afab22a90c42fe09f12628ba3775e9c618f1)
zynthian-sys: [stable (c0f40e8)](https://github.com/zynthian/zynthian-sys/commit/c0f40e82bbed51150a98203ea687034156dfbe15)
zynthian-data: [stable (052465e)](https://github.com/zynthian/zynthian-data/commit/052465ea7283287b8eeb5a15c11046fbcad24465)
zynthian-webconf: [stable (d92c31d)](https://github.com/zynthian/zynthian-webconf/commit/d92c31d304acd97e0a13bbece283093ed50b1774)

**Additional context**
Log:

```
Jul 13 09:51:45 zynthian-v5b startx[532]: ERROR:zynthian_gui.zynswitch_read: [Errno 2] No such file or directory: '/media/root'
Jul 13 09:51:45 zynthian-v5b startx[532]: Traceback (most recent call last):
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1883, in zynswitch_read
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.zynswitches()
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1680, in zynswitches
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.zynswitch_timing(i, dtus)
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1695, in zynswitch_timing
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.zynswitch_short(i)
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1807, in zynswitch_short
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.custom_switch_ui_action(i-4, "S")
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1634, in custom_switch_ui_action
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.callable_ui_action_params(cuia)
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1064, in callable_ui_action_params
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.callable_ui_action(cuia, params)
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1044, in callable_ui_action
Jul 13 09:51:45 zynthian-v5b startx[532]:     cuia_func(params)
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1178, in cuia_toggle_record
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.cuia_toggle_midi_record()
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui.py", line 1160, in cuia_toggle_midi_record
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.screens['midi_recorder'].toggle_recording()
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_midi_recorder.py", line 303, in toggle_recording
Jul 13 09:51:45 zynthian-v5b startx[532]:     if not self.stop_recording():
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_midi_recorder.py", line 294, in stop_recording
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.update_list()
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_selector.py", line 240, in update_list
Jul 13 09:51:45 zynthian-v5b startx[532]:     self.fill_list()
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_midi_recorder.py", line 125, in fill_list
Jul 13 09:51:45 zynthian-v5b startx[532]:     flist += self.get_filelist(self.capture_dir_usb, "USB")
Jul 13 09:51:45 zynthian-v5b startx[532]:   File "/home/pi/zynthian-ui/zyngui/zynthian_gui_midi_recorder.py", line 138, in get_filelist
Jul 13 09:51:45 zynthian-v5b startx[532]:     for f in os.listdir(src_dir):
Jul 13 09:51:45 zynthian-v5b startx[532]: FileNotFoundError: [Errno 2] No such file or directory: '/media/root'
```

**Comment by riban-bw** [comment]
This is fixed in _testing_ branch. We should anticipate such bugs and avoid them taking down the whole subsystem, in this case it stopped buttons from working until a restart. This is a feature of python which will not call functions that have previously uncaught errors. We usually cope with this by wrapping such calls in try/except handlers.
