### ISSUE TITLE
Bug: Uploading SF2 via webconf fails on ORAM

### ISSUE THREAD

**Issue by mheidt** [zynthian/zynthian-issue-tracking#971]
Latest bookworm oram:

Upload a little sf2 file via webconf

Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: ERROR:http1connection.__exit__: Uncaught exception
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: Traceback (most recent call last):
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/http1connection.py", line 662, in _read_f>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     ret = delegate.data_received(body)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/routing.py", line 264, in data_received
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     return self.delegate.data_received(chunk)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 2388, in data_received
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     return self.handler.data_received(data)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/zynthian-webconf/lib/upload_handler.py", line 185, in data_received
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self.ps.data_received(chunk)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornadostreamform/multipart_streamer.py", line 31>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self._feed_part(self.buf[:limit])
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornadostreamform/multipart_streamer.py", line 27>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self.part.feed(data)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornadostreamform/multipart_streamer.py", line 14>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self.f_out.write(data)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/usr/lib/python3.11/tempfile.py", line 622, in func_wrapper
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     return func(*args, **kwargs)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:            ^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: OSError: [Errno 28] No space left on device
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: ERROR:http1connection.__exit__: Uncaught exception
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: Traceback (most recent call last):
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/http1connection.py", line 662, in _read_f>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     ret = delegate.data_received(body)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/routing.py", line 264, in data_received
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     return self.delegate.data_received(chunk)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 2388, in data_received
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     return self.handler.data_received(data)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/zynthian-webconf/lib/upload_handler.py", line 185, in data_received
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self.ps.data_received(chunk)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornadostreamform/multipart_streamer.py", line 31>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self._feed_part(self.buf[:limit])
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornadostreamform/multipart_streamer.py", line 27>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self.part.feed(data)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/zynthian/venv/lib/python3.11/site-packages/tornadostreamform/multipart_streamer.py", line 14>
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     self.f_out.write(data)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:   File "/usr/lib/python3.11/tempfile.py", line 622, in func_wrapper
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:     return func(*args, **kwargs)
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]:            ^^^^^^^^^^^^^^^^^^^^^
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: OSError: [Errno 28] No space left on device
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: DEBUG:zynthian_engine_fluidsynth.get_bank_filelist: LOADING BANK FILES ...
Feb 28 19:26:59 zynthian zynthian_webconf.sh[729]: INFO:web.log_request: 200 POST /lib-presets/upload (192.168.40.136) 28.59ms

**Comment by mheidt** [comment]
@wyleu was quicker:

https://github.com/zynthian/zynthian-issue-tracking/issues/970
