### ISSUE TITLE
Webconf producing 500 errors on many selections...Bug:

### ISSUE THREAD

**Issue by wyleu** [zynthian/zynthian-issue-tracking#978]
# Describe the bug
webconf is producing 500 errors.
# To Reproduce
## Steps to reproduce the behavior:
1. Go to webconf
2. Select Terminal

HTTPServerRequest(protocol='http', host='zynthian-rack.local', method='GET', uri='/zynterm', version='HTTP/1.1', remote_ip='192.168.0.120')
Traceback (most recent call last):
  File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 1788, in _execute
    result = method(*self.path_args, **self.path_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 3301, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/zynthian-webconf/lib/zynterm_handler.py", line 43, in get
    super().get("zynterm.html", "Terminal", config, None)
  File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 3301, in wrapper
    return method(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/zynthian-webconf/lib/zynthian_config_handler.py", line 128, in get
    self.render("config.html", body=body, config=config, title=title, errors=errors)
  File "/zynthian/zynthian-webconf/lib/zynthian_config_handler.py", line 103, in render
    super().render(tpl, info=info, **kwargs)
  File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 944, in render
    html = self.render_string(template_name, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/venv/lib/python3.11/site-packages/tornado/web.py", line 1093, in render_string
    return t.generate(**namespace)
           ^^^^^^^^^^^^^^^^^^^^^^^
  File "/zynthian/venv/lib/python3.11/site-packages/tornado/template.py", line 362, in generate
    return execute()
           ^^^^^^^^^
  File "config_html.generated.py", line 166, in _tt_execute
    for i in config['HARDWARE']['info'].values():  # config.html:130
             ~~~~~~^^^^
```
## Software
```
zyncoder: [oram (a548b43)](https://github.com/zynthian/zyncoder/commit/a548b43251316815ba9c13f9527aa0c311442c4a)
zynthian-ui: [oram (d8f18de)](https://github.com/zynthian/zynthian-ui/commit/d8f18de0dd36f872e72e51ea20792aaa9ebe4d7b)
zynthian-sys: [oram (9922f65)](https://github.com/zynthian/zynthian-sys/commit/9922f652894a097f792acac2c535ec45f74c60a5)
zynthian-data: [oram (64c5f91)](https://github.com/zynthian/zynthian-data/commit/64c5f91bfb55eac7add35e705c72291d4142f332)
zynthian-webconf: [oram (ae7fbc4)](https://github.com/zynthian/zynthian-webconf/commit/ae7fbc4c6f11f71a3ed5c86112b90fff904bb2ff)
```

**Comment by wyleu** [comment]
copy of #979

**Comment by riban-bw** [comment]
Fixed.
